apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: intedesings-online-tls
spec:
  secretName: intedesings-online
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: intedesings.online
  dnsNames:
    - intedesings.online
    - www.intedesings.online
  acme: 
    config:
      - http01:
          ingressClass: nginx
        domains:
          - intedesings.online
          - www.intedesings.online